### ISSUE TITLE
High scores are not working

### ISSUE THREAD

**Issue by O-Deka-K** [devyndamonster/TakeAndHoldTweaker#116]
High scores haven't been working for me for a while now. I've played several different characters on several maps. The BepInEx LogOutput.log says:

> [Info   : Unity Log] Requesting High Score Chart
> [Info   : Unity Log] Requesting High Score Chart
> [Info   : Unity Log] AsyncLoadLevelComplete at:36.48087
> [Error  :TNHTweaker] Something bad happened getting scores 
> Cannot resolve destination host

I looked through the source and it looks like the host may be: https://tnh-dashboard.azure-api.net/v1/api/scores. When I try to go there in my browser, it says "Server Not Found".

**Comment by devyndamonster** [comment]
Sorry, I have taken the high score servers offline permanently due to hosting costs rising to over $50 a month

**Comment by O-Deka-K** [comment]
Okay, thanks
