### ISSUE TITLE
Sausage that starts the game in TnH does not spawn with TakeAndHoldTweaker v1.7.8

### ISSUE THREAD

**Issue by Octomaw** [devyndamonster/TakeAndHoldTweaker#121]

**Comment by RaynorCZE** [comment]
Yep,
Loading Stuck at 100% Caching Stage after saving

**Comment by NecroCloakDozer** [comment]
I managed to fix this in my own testing. Reading through the BepinEx console, it said it was missing a path to write some JSONS. 
If you go into the files of your game, you should find a folder called TNH_Tweaker
If it isnt there, add it, exactly as it is typed there. 
After, you want to add a folder called DefaultCharacters inside of TNH_Tweaker
After running it again and starting the caching process, it auto populated all the JSONS it needed, and TnH worked.

**Comment by Harp797** [comment]
@NecroCloakDozer Thank you so much for your fix. I did what your wrote above, restarted my game, and it worked flawlessly afterwards! much appreciated :D

**Comment by potatoes1286** [comment]
Fixed in 1.7.9- was caused by a silly build mistake in 1.7.8.
