### ISSUE TITLE
Mod compatibility for weapon spawns

### ISSUE THREAD

**Issue by JessicaTheGunLady** [devyndamonster/TakeAndHoldTweaker#2]
It would be nice to have a way to allow for custom weapons to be added as pools without being required, perhaps the mod could check all pools provided, and if a client registers an item as being invalid, then that item will be removed from the pool, or something like that.

**Comment by devyndamonster** [comment]
Could you clarify what you mean by custom weapons? I assume you mean modded weapons, but I don't see how it connects to the rest of your suggestion. As for the second half, I can totally add the ability for characters to have blacklisted items from weapon pools (if that's what you're suggesting).

**Comment by JessicaTheGunLady** [comment]
Apologies, I might've stated things poorly, I was attempting to ask for custom mod-added weapons to be included in weapon pools that forcefully used the ID override in particular, and was proposing a solution of how to do such a thing, vaguely... Possibly... Since I was assuming that if the tables were fed an invalid ID, then they'd just spawn nothing if that ID was selected.

**Comment by devyndamonster** [comment]
Ah, ok. In theory custom weapons would work fine. This might be something that has to be done on the weapon modders end, since the weapons would have to be added to the object dictionary that TNH pulls from.
