### ISSUE TITLE
Multiple items from one purchase

### ISSUE THREAD

**Issue by Trittyburd** [devyndamonster/TakeAndHoldTweaker#24]
Working on a Meat Fortress character, I came upon a possible issue. Dispensers are worthless without a wrench so I would like to have an equipment tippy toy spawn with a wrench so the player has essential equipment. 
Another example but this is more of a me problem, I have a spy-tech purchase column at 5 tokens because the invisiwatch is really good but it can lead to an issue of blowing 11 tokens for two sappers, for now I should just make two different purchase categories.

**Comment by devyndamonster** [comment]
Nice, added it to the roadmap. Just documenting this for my own future self, but another possible use for this would be purchasing complentory loadouts, such as a specific combo of rifle, pistol, and melee weapon. Should be good for themed characters
