### ISSUE TITLE
Have a pool that will only give you compatible magazines for the guns on your body

### ISSUE THREAD

**Issue by devyndamonster** [devyndamonster/TakeAndHoldTweaker#29]

**Comment by LQDvr** [comment]
I would love to have this in the main game much in the way you have ammo and recycle and mag-buy tables to have a mag upgrade table. _`[anton pls]`_ 
In my character I did this by putting the big mp5, g3, g36 and stanag mags as their own rollable item into the slots on the buy table which makes it a lot less likely to get the right mag for the equipped gun in a run.
This is an okay workaround in chars with limited variety of guns / high mag interchangeability but if you can get ANY gun in the game, the likelyhood of encountering the right mag without the game detecting for compatibility is tiny.
