### ISSUE TITLE
Item rarity

### ISSUE THREAD

**Issue by LQDvr** [devyndamonster/TakeAndHoldTweaker#31]
I have done some testing regarding item rarity and it seems the value directly corresponds to how likely an item is to appear on the tables e.g.
`"Rarity": 10.0` appears 10x as much as `"Rarity": 1.0` and `"Rarity": 100.0` appears almost exclusively

In the wiki it is described exactly opposite:

> Sets how likely this pool is to appear. Default is usually 1, and higher values represent rarer pools

**Comment by devyndamonster** [comment]
Thanks for the heads up. The wiki is very out of date, but I will update that part
