### ISSUE TITLE
Take and hold character selection has multiple tabs labled catagory and none of my custom characters

### ISSUE THREAD

**Issue by xXGriffithXx** [devyndamonster/TakeAndHoldTweaker#34]
after the most recent update my take and hold custom characters have been bugged where i cant even select them which never happened with previous updates

**Comment by devyndamonster** [comment]
This likely is happening because one of your characters is outdated. Make sure all of your characters are updated for the latest version. If it still breaks, try launching it with only one character at a time to see which one is causing the issue

**Comment by devyndamonster** [comment]
This has been fixed in the next version of TNH Tweaker (coming soon)
