### ISSUE TITLE
Spawn basic mag from mag upgrader

### ISSUE THREAD

**Issue by OnyxInc** [devyndamonster/TakeAndHoldTweaker#49]
Suggestion: the magazine upgrader should let you spawn the lowest tier magazine (Saiga 5 rnd, AK 10 rnd, etc) for your weapon, for free or for 1 token.

![20201230175722_1](https://user-images.githubusercontent.com/67346262/103472792-416ba800-4d57-11eb-9866-2f69298696aa.jpg)

(Example: PMC Pete drops weapons from enemies, but not with a compatible mag, so they're typically useless)

**Comment by devyndamonster** [comment]
Added a special panel for purchasing magazines, which will serve this purpose
