### ISSUE TITLE
Cant get custom characters

### ISSUE THREAD

**Issue by AlaskaGamer** [devyndamonster/TakeAndHoldTweaker#52]
deli dosent seem to want to run take and hold tweaker for some odd reason i cant get it to work.

**Comment by Sirpotatos** [comment]
This isn't the place for this. Ask for help on the homebrew server on how to properly install it. You have not installed something correctly. TNHTweaker works fine.

**Comment by AlaskaGamer** [comment]
Oh i was posting this becuase i thought it was a bug. I had everything setup properly it just wasnt running. If thats the case am i able to remove this post?
