### ISSUE TITLE
Trying to get the TnH Tweaker to work for the first time but issues came up while Caching.

### ISSUE THREAD

**Issue by anty454** [devyndamonster/TakeAndHoldTweaker#68]
I've been trying to install the TnHTweaker into H3VR but everytime I've waited for the cache to finish up it would usually stop around the 87-88% mark and checking the BepInEx log would give me the following error.

"[Error : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
TNHTweaker.Utilities.TNHTweakerUtils.FVRObjectListContainsID (System.Collections.Generic.List`1 list, System.String objectID)
TNHTweaker.TNHMenuInitializer+<LoadMagazineCacheAsync>d__10.MoveNext ()
AnvilManager+<RunDriven>c__Iterator0.MoveNext ()
UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress)"

Not really code savvy here so does anyone have an explanation in basically why this is stopping the cache loading all of a sudden?

**Comment by devyndamonster** [comment]
Sounds like one of the weapon mods you're using has a null value in one of its fields, so caching can't be completed. The mod author would need to fix that for their gun, but I'll add this issue to the roadmap to make it so that TNH Tweaker lets you know which gun causes the issue.

**Comment by anty454** [comment]
After doing some preliminary and some extra weapons mod removing I've found some of the mods that limited me from loading the cache and after removing them I was able to fully load the cache. (Some of these mods included are not 100% the cause but removing these at least relieved the problem.)

1st Set of Mods removed - (Was able to get the percentage up from 87% to 90%)
Phoenixcraft99's Artic Weapon Mods - https://bonetome.com/h3vr/weapons/369/
Supurfly83's Modern Warfare M4A1- https://bonetome.com/h3vr/weapons/400/

2nd Set of Mods removed - (Finally able to get the percentage from 90% to full loaded cache 100%)
Gaymernayr's Seventh Service Revolver - https://bonetome.com/h3vr/weapons/395/
