### ISSUE TITLE
Modded magazines cause cache fail

### ISSUE THREAD

**Issue by Ijdtm7** [devyndamonster/TakeAndHoldTweaker#83]
Hiya, I just got the new TNHTweaker update and it broke my take and hold. Everything was working fine a few days ago but now when TNHTweaker is installed it fails to cache my magazines from custom mods. 

Here is my log file

[LogOutput.log](https://github.com/devyndamonster/TakeAndHoldTweaker/files/6448014/LogOutput.log)

**Comment by devyndamonster** [comment]
This is caused by an incompatibility between LSIIC and deli.h3vr (which I believe has been updated and renamed to fix this issue)
