### ISSUE TITLE
List of object IDs doesn't exist (404)

### ISSUE THREAD

**Issue by DesiQuintans** [devyndamonster/TakeAndHoldTweaker#91]
I was looking at the wiki to find the object ID for the explosive 12G shells so I can blacklist them, but the list of object IDs that is suggested on [this wiki page](https://github.com/devyndamonster/TakeAndHoldTweaker/wiki/Character-Creation-References#character-creation-tools) (which is supposed to go to [this file](https://github.com/devyndamonster/TakeAndHoldTweaker/blob/master/ObjectIDs.txt)) points to a file that no longer exists.

**Comment by devyndamonster** [comment]
Forgot to update the wiki, this is how you'll want to search for object IDs now: https://github.com/devyndamonster/H3VR-Meta-Viewer

Just click the link in the readme
