### ISSUE TITLE
Ricky'r Dickey'r Randomer requires a TNH Tweaker version that doesn't exist. 1.7.11 IRCC

### ISSUE THREAD

**Issue by HelpMeGetWARZONEONBROWSER** [devyndamonster/TakeAndHoldTweaker#92]

**Comment by devyndamonster** [comment]
This is an issue you'd have to bring up to the maker of Ricky dicky randomer, I have no control over what version of tnh tweaker their character asks for. I'm closing this ticket for now, hope this sent you in the right direction!
